# -*- coding: utf-8 -*-
"""Church_Maps.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11byXbb6LavAaWi0jY70A1aZXB7lINhZt

# Admin details
"""

! pip install gmplot

"""[Address to Lat./Long. Conversion](https://www.gps-coordinates.net/api)

Church Lat./Long.
34.103010, -84.651400

[G4G Geo Plots](https://www.geeksforgeeks.org/python-plotting-google-map-using-gmplot-package/)

# Upwards families

This section plots the families with children registered in the HBC Upwards program.
"""

from gmplot import gmplot

# Place map
gmap = gmplot.GoogleMapPlotter(37.766956, -122.438481, 13)

# Polygon; Rough focus area, may change later
poly_lats, poly_lons = zip(*[
    (34.121387, -84.750460),
    (34.028965, -84.750460),
    (34.028965, -84.562662),
    (34.121387, -84.562662),
    (34.121387, -84.750460)
    ])

gmap.plot(poly_lats, poly_lons, 'cornflowerblue', edge_width=10)

# Scatter points; Addresses coverted to lat/long
top_attraction_lats, top_attraction_lons = zip(*[
    (34.103010, -84.651400),
    (34.103010, -84.651400)
    ])

gmap.scatter(top_attraction_lats, top_attraction_lons, 'cornflowerblue', size=40, marker=False)

# Draw
gmap.draw("upwards_map.html")

"""# Church Members

This produces a plot of the loaction of the church members.
"""

from gmplot import gmplot

# Place map
gmap = gmplot.GoogleMapPlotter(34.103010, -84.651400, 13)

# Scatter points
top_attraction_lats, top_attraction_lons = zip(*[
    (34.09332, -84.57818),
    (34.080060, -84.578750),
    (34.073120, -84.650020),
    (34.108301, -84.62158),
    (34.108301, -84.62158),
    (34.04389953613281, -84.8298568725586),
    (34.04389953613281, -84.8298568725586),
    (34.034322,  -84.77976),
    (34.034322, -84.77976)
    ])
    
gmap.scatter(top_attraction_lats, top_attraction_lons, 'cornflowerblue', size=60, marker=False)

# Draw
gmap.draw("members_map_example.html")

"""# Bus Riders

This section produces a plot of bus riders.
"""

from gmplot import gmplot

# Place map
gmap = gmplot.GoogleMapPlotter(37.766956, -122.438481, 13)

# Scatter points; Addresses coverted to lat/long
top_attraction_lats, top_attraction_lons = zip(*[
    (34.103010, -84.651400),
    (34.103010, -84.651400)
    ])

gmap.scatter(top_attraction_lats, top_attraction_lons, 'cornflowerblue', size=40, marker=False)

# Draw
gmap.draw("upwards_map.html")