# -*- coding: utf-8 -*-
"""Geocoder.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1r65l2U0jR4_DHwwvLZ68fSH9ZPseuegW

# Geocoding via Requests

* Uses Requests to access the Google Maps API
* Uses JS to access the API
* Difficult to use
"""

import requests

url ='https://maps.googleapis.com/maps/api/geocode/json'
params = {'sensor' :'False', 'address' : 'Mountain View, CA'}
r = requests.get(url, params=params)
results = r.json()['results']
location = results[0]['geometry']['location']
location['lat'], location['lng']

"""# Geopy and Geopandas"""

! pip install geopandas

import geopy # Geocoding
import geopandas


def address_to_coordinates(address):
  locator = geopy.Nominatim(user_agent="geocoder_1993")
  location = locator.geocode(address)
  latitude = str(location.latitude)
  longitude = str(location.longitude)
  requested_address = str(location.address)
  altitude = str(location.altitude)
  raw_location = str(location.raw)
  return latitude, longitude, requested_address, altitude


# Google Maps API
#creds = 'AIzaSyA5j7F4tzRq3Y6_80rmKUq2qIMqRyIQz2Q'
#locator = geopy.GoogleV3(api_key=creds)

church_address = {'street':'Kellogg Creek Road', 'city' : 'Acworth', 'county' : 'Cherokee', 'state' : 'Georgia', 'country' : 'USA'}
white_house_address = "1600 Pennsylvania Ave Washington DC, USA"
cherokee_airport_address = "1351 Bishop Road Ball Ground, Georgia USA"
supreme_court_address = "1 First St NE, Washington, DC 20543"

addresses = [church_address, white_house_address, cherokee_airport_address, supreme_court_address]


#try:
for i in addresses:
  try:
    location_obj = address_to_coordinates(i)
    print(location_obj)
  except:
    print('A Geocoding error has occured.')
#except:
#  print('There was an error geocoding.')


#print('Latitude: ' + latitude)
#print('Longitude: ' + longitude)
#print('Address: ' + address)
#print('Approimate altitude: ' + altitude)

