# -*- coding: utf-8 -*-
"""Geocoder.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1r65l2U0jR4_DHwwvLZ68fSH9ZPseuegW
"""

!pip install --upgrade -q gspread

"""# Geocoding

* To convert addresses to lat/long, use geocodio spreadsheet geocoder tool online at [Geocodio](https://dash.geocod.io/). 
* This tool allow 2500 address geocode requests per day free of charge, and charges for requests in excess of 2500 per day.
* See Evernote for account information.
"""

from google.colab import auth
import pandas as pd
import gspread
from oauth2client.client import GoogleCredentials

auth.authenticate_user()
gc = gspread.authorize(GoogleCredentials.get_application_default())


def sheet_import(spreadsheet, sheet_name):
  sh = gc.open(spreadsheet)
  worksheet = sh.worksheet(sheet_name)
  values = worksheet.get_all_values()
  headers = values.pop(0)
  df = pd.DataFrame(values, columns=headers)
  return df

data = sheet_import('Upward_Participants_Geocodio', '3-2-2020')

# get_all_values gives a list of rows.
#rows = worksheet.get_all_values()
#print(rows)

# Convert to a DataFrame and render.
#data = pd.DataFrame.from_records(rows)

data.head()

# General stats
print('Number of values within each column.')
print(data.count())

#Count Unique Addresses by house number, street name
print('Number of unique addresses. ')
print(len(data['Address 1'].unique()))

# Count unique cities
print('Number of unique cities listed. ')
print(len(data['Address 3'].unique()))

# Unique School district LEA codes
print('Number of school district LEA codes. ')
print(len(data['Unified School District LEA code'].unique()))

"""# Data Visualization

## Plot Lat/Long over Map
"""

